### ISSUE TITLE
script close itself in 1 second

### ISSUE THREAD

**Issue by abdo2048** [Cartmanishere/zippyshare-scraper#1]
Hello
I want to thank you very much for your great efforts.

1-I downloaded zippyshare-scraper-master
2- installed python from official site
3- these two packages:
*pip install requests
*pip install bs4
I think first one comes with python setup by default and the I don't know about the second but I downloaded it from here:
https://pypi.org/project/bs4/#files

4- I opened "zippyshare.py" but just cmd screen came to me for 1 second and closed itself!

So pleases, I don't have programming experience ... could you help me?
THANK you very much

**Comment by Cartmanishere** [comment]
You must be missing lxml library. Try -
```pip install lxml```

**Comment by abdo2048** [comment]
Thank you for respond
I have downloaded **"pip install lxml"** from here (latest file on the page)
https://pypi.org/project/lxml/#files
I extracted files then I found a lot of (.py) files, I opend **"setup.py"** (and other files with .py) ... a CMD screen show up that closes after one second, but I managed to take a screen shot before it closes:
https://i.imgur.com/yquoEln.png

So went to http://xmlsoft.org (as INSTALL.txt says) to install **"libxml2"** and **"libxslt"**
I downloaded "libxml2-2.9.8.tar.gz" from here: ftp://xmlsoft.org/libxml2/
I extracted files, but I found a  lot (.py) files, so I opened them (almost all)n but just a CMD show up and no thing happens!

For **"libxslt"** I downloaded **"LATEST_LIBXSLT"** from  ftp://xmlsoft.org/libxml2/ but it just a file with no extension!

Right now "zippyshare-scraper" still not working.

sorry for ignorance.

**Comment by Cartmanishere** [comment]
Okay, I think you're having trouble with the lxml dependency. That's why script isn't working.

I think you should let the package manager handle the installation instead of downloading and running setup.py yourself if you don't have experience in package installation.

What I would recommend is this, run ```pip install lxml``` on your CMD window. And let it handle the installation.

If you're still unable to install the lxml library. Then I'll provide you an alternative- 

``` 
    run 'pip install html-parser' on your cmd window
    open the code in text-editor and wherever your find 'lxml' , replace it with 'html-parser'
```

**Comment by abdo2048** [comment]
Excuse me? what CMD window?
Thanks for replying

**Comment by Cartmanishere** [comment]
I meant your terminal. Run the command in windows shell. Like the one in your screenshot.

**Comment by cooldude1002** [comment]
Hello sir, I have this issue too and I've tried all steps but the script closes itself in 1 second.
When i try to get links i get this message."Total links =17" and then it closes itself.
