### ISSUE TITLE
List of URLs with mixed patterns?

### ISSUE THREAD

**Issue by outhud** [Cartmanishere/zippyshare-scraper#11]
I have a list of zippyshare URLs with different patterns:

> https://www17.zippyshare.com/v/2pJx1Rvd/file.html
> https://www15.zippyshare.com/v/M0nygsaa/file.html
> https://www119.zippyshare.com/v/lNehgCR9/file.html

I think the first 2 are pattern_4 and the 3rd one is pattern_2.

Running this list using --in-file doesn't work. It works OK if I give a file with the first 2 URLs only, or if I give a file with the 3rd URL only.

It seems if I run the in-file with all 3 URLs, it settles on pattern_4 for the first URL, but then assumes all the rest will be also, so it has a problem when it gets to the 3rd URL?

**Comment by name01019** [comment]
I'm having this problem as well

**Comment by name01019** [comment]
[*] Trying next pattern
[*] Trying next pattern
[*] pattern_2 has failed
[*] 1/111 links parsed
[*] Trying next pattern
[*] pattern_3 has failed
[*] Trying next pattern
[*] Starting new HTTPS connection (1): www110.zippyshare.com
[*] 2/111 links parsed
[*] 3/111 links parsed
[*] Starting new HTTPS connection (2): www110.zippyshare.com
[*] 4/111 links parsed
[*] Starting new HTTPS connection (3): www110.zippyshare.com
[*] 5/111 links parsed
[*] Starting new HTTPS connection (4): www110.zippyshare.com
[*] Selected parser pattern_4 failed
[*] Selected parser pattern_4 failed
[*] Selected parser pattern_4 failed
[*] Selected parser pattern_4 failed
[*] Selected parser pattern_4 failed
[*] Selected parser pattern_4 failed
[*] Selected parser pattern_4 failed
Traceback (most recent call last):
  File "zippyshare.py", line 325, in <module>
    links = zippy.parse_links(urls)
  File "zippyshare.py", line 124, in parse_links
    extract, link = f.result()
TypeError: 'NoneType' object is not iterable

**Comment by Sparoney** [comment]
I have this issue as well:

> [*] pattern_1 has failed
> [*] Trying next pattern
> [*] pattern_2 has failed
> [*] Trying next pattern
> [*] pattern_3 has failed
> [*] Trying next pattern
> [*] 1/7 links parsed
> [*] 2/7 links parsed
> [*] 3/7 links parsed
> [*] Selected parser pattern_4 failed
> [*] Selected parser pattern_4 failed
> [*] Selected parser pattern_4 failed
> [*] Selected parser pattern_4 failed
> Traceback (most recent call last):
>   File "zippyshare.py", line 325, in <module>
>     links = zippy.parse_links(urls)
>   File "zippyshare.py", line 124, in parse_links
>     extract, link = f.result()
> TypeError: 'NoneType' object is not iterable

**Comment by Sparoney** [comment]
@outhud @name01019 I have a quick hacky fix before the script is properly updated. Just simply remove `self.parser = parser_fn` from line 84 of the code.

So this:

>             for parser_fn in parsers:
>                 try:
>                     extract = parser_fn(soup)
>                     if extract is not None:
>                         self.parser = parser_fn
>                         return extract, link
>                     raise Exception
becomes:

>             for parser_fn in parsers:
>                 try:
>                     extract = parser_fn(soup)
>                     if extract is not None:
>                         return extract, link
>                     raise Exception

This makes every link go through all four patterns, regardless if the previous links worked.

**Comment by Cartmanishere** [comment]
This is weird. Usually all URLs follow the same pattern and this has always worked. 

If Zippyshare has changed something so that some URLs follow one pattern and other URLs something different, then you'd have to check which pattern it is for all the URLs.

In such a case, I think what @Sparoney did would be a quick solution. I'll investigate more on this.
