### ISSUE TITLE
All patterns now do not work 

### ISSUE THREAD

**Issue by name01019** [Cartmanishere/zippyshare-scraper#12]
[*] pattern_1 has failed
[*] Trying next pattern
[*] pattern_2 has failed
[*] Trying next pattern
[*] pattern_3 has failed
[*] Trying next pattern
[*] pattern_4 has failed
[*] Trying next pattern
[*] All patterns have failed

**Comment by Cartmanishere** [comment]
Updated the code. Please try now.
