### ISSUE TITLE
Questions about installation

### ISSUE THREAD

**Issue by name01019** [Cartmanishere/zippyshare-scraper#14]
For some reason, I'm having trouble setting up a fresh Ubuntu machine. I ran the following right after installing Ubuntu.
**sudo apt-get update
sudo apt-get install -y python3
sudo apt-get install -y python3-pip
pip3 install requests
pip3 install bs4
sudo apt-get install -y aria2
sudo apt-get install -y python3-lxml**

Then, I ran **python3 zippyshare.py --dlc file.dlc**

This is what I get (links removed)
**[*] pattern_1 has failed for link: https://www2.zippyshare.com/v/***/file.html
[*] Trying next pattern
[*] pattern_2 has failed for link: https://www2.zippyshare.com/v/***/file.html
[*] Trying next pattern
[*] pattern_3 has failed for link: https://www2.zippyshare.com/v/***/file.html
[*] Trying next pattern
[*] pattern_4 has failed for link: https://www2.zippyshare.com/v/***/file.html
[*] Trying next pattern
[*] pattern_5 has failed for link: https://www2.zippyshare.com/v/***/file.html
[*] Trying next pattern
[*] pattern_6 has failed for link: https://www2.zippyshare.com/v/***/file.html
[*] Trying next pattern
[*] All patterns have failed
[*] Failed to parse - https://www2.zippyshare.com/v/***/file.html**

The strange thing is that the same command and dlc file worked for an old Ubuntu machine I use, so I'm really confused why my installation failed. Any ideas?

**Comment by arNayeem** [comment]
I am getting this error. I have installed bs4 and requests in python 3.8 in windows
Traceback (most recent call last):
  File "zs.py", line 398, in <module>
    links, failed = zippy.parse_links(urls)
  File "zs.py", line 128, in parse_links
    extract, link = f.result()
  File "C:\Users\Nayeem\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\Users\Nayeem\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:\Users\Nayeem\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "zs.py", line 64, in get_download_link
    soup = BeautifulSoup(html.content, "lxml")
  File "C:\Users\Nayeem\AppData\Local\Programs\Python\Python38-32\lib\site-packages\bs4\__init__.py", line 225, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by name01019** [comment]
arNayeem, you need to install lxml
Run **pip3 install lxml** and try again

**Comment by NullBruce** [comment]
@name01019  i get this
pattern_1 has failed for link: https://www84.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/file.html
[*] Trying next pattern
[*] pattern_2 has failed for link: https://www84.zipxxxxxxxxxxxxxxxxxxxxxxxxxtml
[*] Trying next pattern
[*] pattern_3 has failed for link: https://www84.zipxxxxxxxxxxxxxxxxxxxxxxxxxx
[*] Trying next pattern
[*] pattern_4 has failed for link: https://www84.zippxxxxxxxxxxxxxxxxxxxxx
[*] Trying next pattern
[*] pattern_5 has failed for link: https://www84.zippyxxxxxxxxxxxxxxxxxxxxxxx
[*] Trying next pattern
[*] pattern_6 has failed for link: https://www84.zippysxxxxxxxxxxxxxxxx
[*] Trying next pattern
[*] All patterns have failed
[*] Failed to parse - https://www84.zippyxxxxxxxxxxxx
[*] Verifying download links...
[*] All download links saved at links.txt

**Comment by name01019** [comment]
Found a solution

Run
**sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y dist-upgrade
sudo apt-get install -y python3
sudo apt-get install -y python3-requests
sudo apt-get install -y python3-bs4**
