### ISSUE TITLE
dcrypt.it

### ISSUE THREAD

**Issue by name01019** [Cartmanishere/zippyshare-scraper#15]
I've noticed that this script goes to http://dcrypt.it/decrypt/paste to decrypt dlc containers. Sometimes when running the scraper though, it fails to scrape all the links in a dlc container, forcing me to re-run the script multiple times. This calls dcrypt.it more than necessary, sometimes making the server lock me out.

Can you amend the script so that it produces another file "decrypted-[name of dlc].txt" so that I won't have to keep going to dcrypt.it?

**Comment by Cartmanishere** [comment]
Ok. I will look into it. Do you have a reproducible example for when it fails to scrape all the links in a dlc container? It would help in identifying why it would happen. Also I think it makes sense to create an intermediate files for dlc decrypted links.

**Comment by name01019** [comment]
Nope sorry, I don't have the command line result anymore. You can reproduce it though if you keep spamming dcrypt.it over a short time. I think it's a DDoS protection mechanism.

**Comment by Cartmanishere** [comment]
Most likely. Please don't DDoS [decryp.it](http://dcrypt.it/).

One thing I can do to mitigate this is cache the decryption results for a while. This way, next time you retry for the same dlc file, it won't go to their API.
