### ISSUE TITLE
Failed to Parse all 6 patterns

### ISSUE THREAD

**Issue by Thiago-Heleno** [Cartmanishere/zippyshare-scraper#16]
This is the Url i tried: https://www10.zippyshare.com/v/f3qwAQAG/file.html

**Comment by MilkyWay1133** [comment]
same here

**Comment by Sorrow446** [comment]
I slapped up a Bsoup / JS execution-free script. Tried a bunch of links, including your one above, worked fine. I'll update this when I polish it up some more.

**Comment by Cartmanishere** [comment]
@Thiago-Heleno @Richie-Z Sorry this took so long. 

I have added a quick fix to make it work with the link @Thiago-Heleno had provided.

Please check it out. And I'll try to have less turn around time whenever this stops working next time.
