### ISSUE TITLE
Software no longer working on any zippyshare link

### ISSUE THREAD

**Issue by kangtheconqueror2** [Cartmanishere/zippyshare-scraper#2]
I've been using this script without issue for a few weeks now, however as of two days ago, every link i input on any of the three methods (even those links that i have previously successfully downloaded from) gives an error as shown in the attached pictures.
<img width="960" alt="1" src="https://user-images.githubusercontent.com/39931808/40948373-9a87bc7a-6881-11e8-83b3-6ea37c4e1675.png">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/39931808/40948374-9ab8ff92-6881-11e8-9516-c6d7dced5857.png">
<img width="960" alt="3" src="https://user-images.githubusercontent.com/39931808/40948375-9b14ad1a-6881-11e8-9fe7-afdb372ad6bf.png">

**Comment by Cartmanishere** [comment]
Yes, they recently changed their source code. I have updated the script which will work with the new source code. Please try the new script. If you face any problems, open another issue. I'm closing this one.

**Comment by kangtheconqueror2** [comment]
Hi, thank you for your reply. The new script was working great.
Unfortunately since yesterday its started giving another similar error:
REGEX_4 (please see attached picture)
This error shows up for all three of the options. I have tried it with a
combination of different zippyshare links and the error shows up for all of
them unfortunately.
