### ISSUE TITLE
None of the patterns are working

### ISSUE THREAD

**Issue by PotatoesGonnaPotaet** [Cartmanishere/zippyshare-scraper#23]
Hi, I tried to get the DDLs from a dlc but was not able to. It tries the patterns and outputs "All Patterns Failed" for all the links. I've pasted the output for one link as below

```
python zippyshare.py
Enter URLs (leave blank to stop): https://www61.zippyshare.com/v/t84fjr8d/file.html
Enter URLs (leave blank to stop):
[!] REGEX_1 failed for pattern #1
[*] pattern_1 has failed for link: https://www61.zippyshare.com/v/t84fjr8d/file.html
[*] Trying next pattern
[!] REGEX_1 failed for pattern #2
[*] pattern_2 has failed for link: https://www61.zippyshare.com/v/t84fjr8d/file.html
[*] Trying next pattern
[!] REGEX_1 failed for pattern #3
[*] pattern_3 has failed for link: https://www61.zippyshare.com/v/t84fjr8d/file.html
[*] Trying next pattern
[!] REGEX_1 failed for pattern #4
[*] pattern_4 has failed for link: https://www61.zippyshare.com/v/t84fjr8d/file.html
[*] Trying next pattern
[!] REGEX_1 failed for pattern #5
[*] pattern_5 has failed for link: https://www61.zippyshare.com/v/t84fjr8d/file.html
[*] Trying next pattern
[!] REGEX_1 failed for pattern #6
[*] pattern_6 has failed for link: https://www61.zippyshare.com/v/t84fjr8d/file.html
[*] Trying next pattern
[!] REGEX_1 failed for pattern #7
[*] pattern_7 has failed for link: https://www61.zippyshare.com/v/t84fjr8d/file.html
[*] Trying next pattern
[*] All patterns have failed
[*] Failed to parse - https://www61.zippyshare.com/v/t84fjr8d/file.html
[*] Verifying download links...
[*] All download links saved at links.txt
[*] All failed links saved at failed.log
```
I tried it with a .dlc file first but it has around 200 links all with the same result.

Additionally, the program for some reason is not identifying ```--dlc-file``` as a valid input

```
python zippyshare.py --dlc-file "C:\Users\username\Downloads\f91ddc57a78414c162378996348be2a2457f5a88.dlc"
usage: zippyshare.py [-h] [--in-file INFILE] [--out-file OUTFILE] [--dlc DLCFILE]
zippyshare.py: error: unrecognized arguments: --dlc-file C:\Users\adilk\Downloads\f91ddc57a78414c162378996348be2a2457f5a88.dlc
```

```--dlc``` is working to get the links from a dlc container. 

Thanks for your work though. :)

**Comment by Cartmanishere** [comment]
Ah, I think the arg got renamed. Thanks for pointing out.

The links seems to be working now. Unless I can get an example link which fails for me, I can't really debug what's the issue.

**Comment by PotatoesGonnaPotaet** [comment]
> Ah, I think the arg got renamed. Thanks for pointing out.

Welcome :)

This is one of the links I've been trying. It still doesn't seem to work for me which makes me question if I'm doing something wrong. Please let me know if this works for you and until then I'll try to figure if the issue is on my end.  

`http://www4.zippyshare.com/v/BJeyL1RB/file.html`

**Comment by Cartmanishere** [comment]
@PotatoesGonnaPotaet even these link seem to be working for me. Now I wonder if Zippyshare changes some things based on geographic region. Out of curiosity, from which region are you accessing?

In order for me to debug, can you try this.
- Open the link which is not working in your browser.
- View source code for that page.
- And send me the HTML source code for that page (a [pastebin.com](https://pastebin.com) link will work)

We'll see if there are any differences between what I'm seeing and what you are seeing.

**Comment by PotatoesGonnaPotaet** [comment]
@Cartmanishere yea I think you are right about the geographic region thing. I'm in Germany where the site is blocked. However, I usually use a VPN to circumvent that restriction and download it. My usual method is to use JDownloader2 for downloading, after connecting to VPN of course. 

I have tried several servers from many countries but came to same result with the package. Unfortunately, I am not sure if CMD is routing through VPN or not, and I have no idea how to make it route through the VPN (I hope that makes sense). 

Anyways, here's the link to the HTML source code for that page. I hope this is the same one as you requested.

[Link to HTML](https://pastebin.com/QXBnGykr)

**Comment by Cartmanishere** [comment]
@PotatoesGonnaPotaet I see no problem with the HTML you have linked. This matches `pattern_6` and should be handled correctly. 

I had assumed so but just to confirm, you are working with the latest code right?

If not, try with a fresh clone of this repo from the master.

**Comment by PotatoesGonnaPotaet** [comment]
@Cartmanishere  Yep, I tried once again to confirm.

Just to be sure, is the one that was updated on Aug 22 right (3 months ago)? I'm sorry I'm quite new to this and since there were no releases, I just downloaded the one that was available on the main page (code > Download Zip).

**Comment by RyanzpLee** [comment]
I'm also having difficulty with the script failing to parse the link
`python zippyshare.py
Enter URLs (leave blank to stop): https://www114.zippyshare.com/v/b37VskqN/file.html
Enter URLs (leave blank to stop):
[!] REGEX_1 failed for pattern #1
[*] pattern_1 has failed for link: https://www114.zippyshare.com/v/b37VskqN/file.html
[*] Trying next pattern
[!] REGEX_1 failed for pattern #2
[*] pattern_2 has failed for link: https://www114.zippyshare.com/v/b37VskqN/file.html
[*] Trying next pattern
[!] REGEX_1 failed for pattern #3
[*] pattern_3 has failed for link: https://www114.zippyshare.com/v/b37VskqN/file.html
[*] Trying next pattern
[!] REGEX_1 failed for pattern #4
[*] pattern_4 has failed for link: https://www114.zippyshare.com/v/b37VskqN/file.html
[*] Trying next pattern
[!] REGEX_1 failed for pattern #5
[*] pattern_5 has failed for link: https://www114.zippyshare.com/v/b37VskqN/file.html
[*] Trying next pattern
[!] REGEX_1 failed for pattern #6
[*] pattern_6 has failed for link: https://www114.zippyshare.com/v/b37VskqN/file.html
[*] Trying next pattern
[!] REGEX_1 failed for pattern #7
[*] pattern_7 has failed for link: https://www114.zippyshare.com/v/b37VskqN/file.html
[*] Trying next pattern
[*] All patterns have failed
[*] Failed to parse - https://www114.zippyshare.com/v/b37VskqN/file.html
[*] Verifying download links...
[*] All download links saved at links.txt
[*] All failed links saved at failed.log`

[Here is the link the source code of page](https://pastebin.com/19dSpRaY)

I have cloned the latest version of this repo, and I'm currently on Windows 10 running python 3.9.0 in a virtual environment. Hope you can help, thanks!

**Comment by Cartmanishere** [comment]
Please try this with new code. If It doesn't work, open a new issue.
