### ISSUE TITLE
Please add extra opption

### ISSUE THREAD

**Issue by de2apandi** [Cartmanishere/zippyshare-scraper#25]
Hello. 
Thanks for great scrapper, 👍
Is possible add extra extraction from **filecrypt.cc**

Thanks before.

**Comment by Cartmanishere** [comment]
Hi,

I have faced a similar issue before. Having to download the dlc and then running the script is a bit of a pain.

I have added option where you can directly specify the filecrypt URL.

Ofc it won't work if the url is password or captcha protected.
