### ISSUE TITLE
REGEX_4 Failed. 

### ISSUE THREAD

**Issue by backslash033** [Cartmanishere/zippyshare-scraper#3]
While using the script i got this error, was working fine yesterday but today it says "REGEX_4 Failed"
![err](https://user-images.githubusercontent.com/29457182/41405066-7dc82ec8-6fe6-11e8-9667-5dccfcde8c3f.png)

**Comment by Cartmanishere** [comment]
Hi, I just made a latest commit. 

Please use the ```zippyshare_1.py``` file to decode links. This should work for now.

In the future, if source code is changed. Try running the alternative scripts that I have provided and if they won't work either, open up a issue and I'll fix the code.

**Comment by backslash033** [comment]
Thank you, it's much appreciated.
