### ISSUE TITLE
Regex failing

### ISSUE THREAD

**Issue by tyeeman** [Cartmanishere/zippyshare-scraper#5]
I think they changed their code again, yes? Tried all 3 scripts.

**Comment by Exodion** [comment]
@tyeeman Try the new zippyshare_1.py script. It's working for me.

**Comment by Aaron34789** [comment]
zippyshare_1.py script seems to be working. Thanks Pranav for fixing the issue.

**Comment by tyeeman** [comment]
Thanks, works great now! BTW, I use aria2c lots also but get errors when I give it https links. Is there a way to get aria2c to use the secure links?

**Comment by Exodion** [comment]
@tyeeman I use aria2 all the time with HTTPS links. Maybe run it with `--min-tls-version=TLSv1.2`

**Comment by tyeeman** [comment]
My version was nearly 3 years old, I downloaded the newest and it seems to work now. Thanks.
